#!/bin/bash

# URLs to check
URLS=(
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/websocket-api/request-security"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/websocket-api/session-authentication"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/websocket-api/data-sources"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/websocket-api/general-requests"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/websocket-api/trading-requests"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/websocket-api/account-requests"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/websocket-api/user-data-stream-requests"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/web-socket-streams"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/sbe-market-data-streams"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/errors"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/TESTNET-TERMS-OF-USE"
"https://developers.binance.com/docs/binance-spot-api-docs/PROD-TERMS-OF-USE"
"https://developers.binance.com/docs/binance-spot-api-docs/demo-mode"
"https://developers.binance.com/docs/binance-spot-api-docs/demo-mode/general-info"
"https://developers.binance.com/docs/binance-spot-api-docs/demo-mode/DEMO-TERMS-OF-USE"
"https://developers.binance.com/docs/binance-spot-api-docs/errors"
"https://developers.binance.com/docs/binance-spot-api-docs/faqs/spot_glossary"
"https://developers.binance.com/docs/binance-spot-api-docs/faqs/pegged_orders"
"https://developers.binance.com/docs/binance-spot-api-docs/faqs/opo"
"https://developers.binance.com/docs/binance-spot-api-docs/faqs/commission_faq"
"https://developers.binance.com/docs/binance-spot-api-docs/faqs/trailing-stop-faq"
"https://developers.binance.com/docs/binance-spot-api-docs/faqs/stp_faq"
"https://developers.binance.com/docs/binance-spot-api-docs/faqs/market_data_only"
"https://developers.binance.com/docs/binance-spot-api-docs/faqs/sor_faq"
"https://developers.binance.com/docs/binance-spot-api-docs/faqs/order_count_decrement"
"https://developers.binance.com/docs/binance-spot-api-docs/faqs/sbe_faq"
"https://developers.binance.com/docs/binance-spot-api-docs/faqs/api_key_types"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/websocket-api/rate-limits"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/websocket-api/event-format"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/websocket-api/response-format"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/websocket-api/request-format"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/websocket-api/general-api-information"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/user-data-stream"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/fix-api"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/rest-api/account-endpoints"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/rest-api/trading-endpoints"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/rest-api/market-data-endpoints"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/rest-api/general-endpoints"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/rest-api/request-security"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/rest-api/data-sources"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/rest-api/limits"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/rest-api/general-information-on-endpoints"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/rest-api/error-codes"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/rest-api/http-return-codes"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/rest-api/general-api-information"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/enums"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/filters"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet/general-info"
"https://developers.binance.com/docs/binance-spot-api-docs/testnet"
"https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/user-data-stream-requests"
"https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/account-requests"
"https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/trading-requests"
"https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/authentication-requests"
"https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/market-data-requests"
"https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/general-requests"
"https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/data-sources"
"https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/session-authentication"
"https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/request-security"
"https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/rate-limits"
"https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/event-format"
"https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/response-format"
"https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/request-format"
"https://developers.binance.com/docs/binance-spot-api-docs/websocket-api/general-api-information"
"https://developers.binance.com/docs/binance-spot-api-docs/user-data-stream"
"https://developers.binance.com/docs/binance-spot-api-docs/sbe-market-data-streams"
"https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams"
"https://developers.binance.com/docs/binance-spot-api-docs/fix-api"
"https://developers.binance.com/docs/binance-spot-api-docs/rest-api/account-endpoints"
"https://developers.binance.com/docs/binance-spot-api-docs/rest-api/trading-endpoints"
"https://developers.binance.com/docs/binance-spot-api-docs/rest-api/market-data-endpoints"
"https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-endpoints"
"https://developers.binance.com/docs/binance-spot-api-docs/rest-api/request-security"
"https://developers.binance.com/docs/binance-spot-api-docs/rest-api/data-sources"
"https://developers.binance.com/docs/binance-spot-api-docs/rest-api/limits"
"https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-information-on-endpoints"
"https://developers.binance.com/docs/binance-spot-api-docs/rest-api/error-codes"
"https://developers.binance.com/docs/binance-spot-api-docs/rest-api/http-return-codes"
"https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information"
"https://developers.binance.com/docs/binance-spot-api-docs/enums"
"https://developers.binance.com/docs/binance-spot-api-docs/filters"
"https://developers.binance.com/docs/binance-spot-api-docs/README"
"https://developers.binance.com/docs/binance-pay/introduction"
"https://developers.binance.com/docs/binance-w3w/evm-compatible-provider"
"https://developers.binance.com/docs/rebate/Introduction"
"https://developers.binance.com/docs/vip_loan/Introduction"
"https://developers.binance.com/docs/link_plus/change-log"
"https://developers.binance.com/docs/sub_account/Introduction"
"https://developers.binance.com/docs/wallet/Introduction"
"https://developers.binance.com/docs/binance-open-api/scopes"
"https://developers.binance.com/docs/w3w_web3_dapp/self-listing"
"https://developers.binance.com/docs/babt/introduction"
"https://developers.binance.com/docs/crypto_loan/Introduction"
"https://developers.binance.com/docs/fund_account/change-log"
"https://developers.binance.com/docs/alpha/change-log"
"https://developers.binance.com/docs/algo/Introduction"
"https://developers.binance.com/docs/mini-program/quick-start"
"https://developers.binance.com/docs/cms/cms-log"
"https://developers.binance.com/docs/gift_card/Introduction"
"https://developers.binance.com/docs/mining/Introduction"
"https://developers.binance.com/docs/vip_services/change-log"
"https://developers.binance.com/docs/institutional_loan/Introduction"
"https://developers.binance.com/docs/margin_trading/Introduction"
"https://developers.binance.com/docs/connect_prime/introduction"
"https://developers.binance.com/docs/w3w_open_platform/self-listing-op"
"https://developers.binance.com/docs/pay/Introduction"
"https://developers.binance.com/docs/fiat/Introduction"
"https://developers.binance.com/docs/advanced_earn/Introduction"
"https://developers.binance.com/docs/spot_block_match/change-log"
"https://developers.binance.com/docs/convert/Introduction"
"https://developers.binance.com/docs/derivatives/Introduction"
"https://developers.binance.com/docs/binance_connect/introduction"
"https://developers.binance.com/docs/w3w_task_verification_api/apis"
"https://developers.binance.com/docs/simple_earn/Introduction"
"https://developers.binance.com/docs/c2c/Introduction"
"https://developers.binance.com/docs/staking/Introduction"
"https://developers.binance.com/docs/binance_link/change-log"
"https://developers.binance.com/docs/copy_trading/Introduction"
"https://developers.binance.com/docs/binance-spot-api-docs/CHANGELOG"
)

BASE_DIR="/home/z/my-project/docs/exchange/binance"

echo "Total URLs to check: ${#URLS[@]}"
echo ""

count=0
for url in "${URLS[@]}"; do
    # Extract path after /docs/
    path=$(echo "$url" | sed 's|https://developers.binance.com/docs/||')
    
    # Convert to file path
    file_path="$BASE_DIR/${path}.md"
    
    if [ -f "$file_path" ]; then
        size=$(wc -c < "$file_path")
        echo "✓ EXISTS: $path ($size bytes)"
    else
        echo "✗ MISSING: $path"
        ((count++))
    fi
done

echo ""
echo "Missing files: $count"
